-- DROP TABLE IF EXISTS `account`;
CREATE TABLE `account` (
	`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
	`username` VARCHAR(200) NOT NULL COMMENT '用户名称',
	`balance` INT NOT NULL COMMENT '余额',
	PRIMARY KEY(`id`)
)ENGINE=INNODB;

-- DROP TABLE IF EXISTS `book`;
CREATE TABLE `book`(
	`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
	`name` VARCHAR(200) NOT NULL COMMENT '书名',
	`price` INT NOT NULL COMMENT '价格',
	PRIMARY KEY(`id`)
)ENGINE=INNODB;

-- DROP TABLE IF EXISTS `book_stock`;
CREATE TABLE `book_stock`(
	`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
	`book_id` BIGINT NOT NULL COMMENT '关联bookID',
	`stock` INT NOT NULL COMMENT '库存',
	PRIMARY KEY(`id`)
)ENGINE=INNODB;